/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'com.kodfarki.subscreasy.client.model/CompanyProps'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../com.kodfarki.subscreasy.client.model/CompanyProps'));
  } else {
    // Browser globals (root is window)
    if (!root.SubscreasyJsClient) {
      root.SubscreasyJsClient = {};
    }
    root.SubscreasyJsClient.CompanyPropsResourceApi = factory(root.SubscreasyJsClient.ApiClient, root.SubscreasyJsClient.CompanyProps);
  }
}(this, function(ApiClient, CompanyProps) {
  'use strict';

  /**
   * CompanyPropsResource service.
   * @module com.kodfarki.subscreasy.client/CompanyPropsResourceApi
   * @version 1.0.0
   */

  /**
   * Constructs a new CompanyPropsResourceApi. 
   * @alias module:com.kodfarki.subscreasy.client/CompanyPropsResourceApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createCompanyPropsUsingPOST operation.
     * @callback module:com.kodfarki.subscreasy.client/CompanyPropsResourceApi~createCompanyPropsUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:com.kodfarki.subscreasy.client.model/CompanyProps} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * createCompanyProps
     * @param {module:com.kodfarki.subscreasy.client.model/CompanyProps} companyProps companyProps
     * @param {module:com.kodfarki.subscreasy.client/CompanyPropsResourceApi~createCompanyPropsUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.kodfarki.subscreasy.client.model/CompanyProps}
     */
    this.createCompanyPropsUsingPOST = function(companyProps, callback) {
      var postBody = companyProps;

      // verify the required parameter 'companyProps' is set
      if (companyProps === undefined || companyProps === null) {
        throw new Error("Missing the required parameter 'companyProps' when calling createCompanyPropsUsingPOST");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apiKey'];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = CompanyProps;

      return this.apiClient.callApi(
        '/api/company-props', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteCompanyPropsUsingDELETE operation.
     * @callback module:com.kodfarki.subscreasy.client/CompanyPropsResourceApi~deleteCompanyPropsUsingDELETECallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * deleteCompanyProps
     * @param {Number} id id
     * @param {module:com.kodfarki.subscreasy.client/CompanyPropsResourceApi~deleteCompanyPropsUsingDELETECallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteCompanyPropsUsingDELETE = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteCompanyPropsUsingDELETE");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apiKey'];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/company-props/{id}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllCompanyPropsUsingGET operation.
     * @callback module:com.kodfarki.subscreasy.client/CompanyPropsResourceApi~getAllCompanyPropsUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:com.kodfarki.subscreasy.client.model/CompanyProps>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getAllCompanyProps
     * @param {module:com.kodfarki.subscreasy.client/CompanyPropsResourceApi~getAllCompanyPropsUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:com.kodfarki.subscreasy.client.model/CompanyProps>}
     */
    this.getAllCompanyPropsUsingGET = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apiKey'];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = [CompanyProps];

      return this.apiClient.callApi(
        '/api/company-props', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getCompanyPropsByCompanyIdUsingGET operation.
     * @callback module:com.kodfarki.subscreasy.client/CompanyPropsResourceApi~getCompanyPropsByCompanyIdUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:com.kodfarki.subscreasy.client.model/CompanyProps} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getCompanyPropsByCompanyId
     * @param {Number} companyId companyId
     * @param {module:com.kodfarki.subscreasy.client/CompanyPropsResourceApi~getCompanyPropsByCompanyIdUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.kodfarki.subscreasy.client.model/CompanyProps}
     */
    this.getCompanyPropsByCompanyIdUsingGET = function(companyId, callback) {
      var postBody = null;

      // verify the required parameter 'companyId' is set
      if (companyId === undefined || companyId === null) {
        throw new Error("Missing the required parameter 'companyId' when calling getCompanyPropsByCompanyIdUsingGET");
      }


      var pathParams = {
        'companyId': companyId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apiKey'];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = CompanyProps;

      return this.apiClient.callApi(
        '/api/company-props/company/{companyId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateCompanyPropsUsingPUT operation.
     * @callback module:com.kodfarki.subscreasy.client/CompanyPropsResourceApi~updateCompanyPropsUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:com.kodfarki.subscreasy.client.model/CompanyProps} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updateCompanyProps
     * @param {module:com.kodfarki.subscreasy.client.model/CompanyProps} companyProps companyProps
     * @param {module:com.kodfarki.subscreasy.client/CompanyPropsResourceApi~updateCompanyPropsUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.kodfarki.subscreasy.client.model/CompanyProps}
     */
    this.updateCompanyPropsUsingPUT = function(companyProps, callback) {
      var postBody = companyProps;

      // verify the required parameter 'companyProps' is set
      if (companyProps === undefined || companyProps === null) {
        throw new Error("Missing the required parameter 'companyProps' when calling updateCompanyPropsUsingPUT");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apiKey'];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = CompanyProps;

      return this.apiClient.callApi(
        '/api/company-props', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
