/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Company from '../com.kodfarki.subscreasy.client.model/Company';

/**
* CompanyResource service.
* @module com.kodfarki.subscreasy.client/CompanyResourceApi
* @version 1.0.0
*/
export default class CompanyResourceApi {

    /**
    * Constructs a new CompanyResourceApi. 
    * @alias module:com.kodfarki.subscreasy.client/CompanyResourceApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createCompanyUsingPOST operation.
     * @callback module:com.kodfarki.subscreasy.client/CompanyResourceApi~createCompanyUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:com.kodfarki.subscreasy.client.model/Company} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * createCompany
     * @param {module:com.kodfarki.subscreasy.client.model/Company} company company
     * @param {module:com.kodfarki.subscreasy.client/CompanyResourceApi~createCompanyUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.kodfarki.subscreasy.client.model/Company}
     */
    createCompanyUsingPOST(company, callback) {
      let postBody = company;
      // verify the required parameter 'company' is set
      if (company === undefined || company === null) {
        throw new Error("Missing the required parameter 'company' when calling createCompanyUsingPOST");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Company;
      return this.apiClient.callApi(
        '/api/companies', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteCompanyUsingDELETE operation.
     * @callback module:com.kodfarki.subscreasy.client/CompanyResourceApi~deleteCompanyUsingDELETECallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * deleteCompany
     * @param {Number} id id
     * @param {module:com.kodfarki.subscreasy.client/CompanyResourceApi~deleteCompanyUsingDELETECallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteCompanyUsingDELETE(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteCompanyUsingDELETE");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/companies/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllCompaniesUsingGET operation.
     * @callback module:com.kodfarki.subscreasy.client/CompanyResourceApi~getAllCompaniesUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:com.kodfarki.subscreasy.client.model/Company>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getAllCompanies
     * @param {module:com.kodfarki.subscreasy.client/CompanyResourceApi~getAllCompaniesUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:com.kodfarki.subscreasy.client.model/Company>}
     */
    getAllCompaniesUsingGET(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [Company];
      return this.apiClient.callApi(
        '/api/companies', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getCompanyUsingGET operation.
     * @callback module:com.kodfarki.subscreasy.client/CompanyResourceApi~getCompanyUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:com.kodfarki.subscreasy.client.model/Company} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getCompany
     * @param {Number} id id
     * @param {module:com.kodfarki.subscreasy.client/CompanyResourceApi~getCompanyUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.kodfarki.subscreasy.client.model/Company}
     */
    getCompanyUsingGET(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getCompanyUsingGET");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = Company;
      return this.apiClient.callApi(
        '/api/companies/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateCompanyUsingPUT operation.
     * @callback module:com.kodfarki.subscreasy.client/CompanyResourceApi~updateCompanyUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:com.kodfarki.subscreasy.client.model/Company} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updateCompany
     * @param {module:com.kodfarki.subscreasy.client.model/Company} company company
     * @param {module:com.kodfarki.subscreasy.client/CompanyResourceApi~updateCompanyUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.kodfarki.subscreasy.client.model/Company}
     */
    updateCompanyUsingPUT(company, callback) {
      let postBody = company;
      // verify the required parameter 'company' is set
      if (company === undefined || company === null) {
        throw new Error("Missing the required parameter 'company' when calling updateCompanyUsingPUT");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Company;
      return this.apiClient.callApi(
        '/api/companies', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
