/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'com.kodfarki.subscreasy.client.model/CreateOrderRequest', 'com.kodfarki.subscreasy.client.model/Order'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../com.kodfarki.subscreasy.client.model/CreateOrderRequest'), require('../com.kodfarki.subscreasy.client.model/Order'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.OrderResourceApi = factory(root.ApiDocumentation.ApiClient, root.ApiDocumentation.CreateOrderRequest, root.ApiDocumentation.Order);
  }
}(this, function(ApiClient, CreateOrderRequest, Order) {
  'use strict';

  /**
   * OrderResource service.
   * @module com.kodfarki.subscreasy.client/OrderResourceApi
   * @version 1.0
   */

  /**
   * Constructs a new OrderResourceApi. 
   * @alias module:com.kodfarki.subscreasy.client/OrderResourceApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createOrderUsingPOST operation.
     * @callback module:com.kodfarki.subscreasy.client/OrderResourceApi~createOrderUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:com.kodfarki.subscreasy.client.model/Order} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * createOrder
     * @param {module:com.kodfarki.subscreasy.client.model/CreateOrderRequest} orderRequest orderRequest
     * @param {module:com.kodfarki.subscreasy.client/OrderResourceApi~createOrderUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.kodfarki.subscreasy.client.model/Order}
     */
    this.createOrderUsingPOST = function(orderRequest, callback) {
      var postBody = orderRequest;

      // verify the required parameter 'orderRequest' is set
      if (orderRequest === undefined || orderRequest === null) {
        throw new Error("Missing the required parameter 'orderRequest' when calling createOrderUsingPOST");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apiKey'];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = Order;

      return this.apiClient.callApi(
        '/api/orders', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllOrdersUsingGET operation.
     * @callback module:com.kodfarki.subscreasy.client/OrderResourceApi~getAllOrdersUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:com.kodfarki.subscreasy.client.model/Order>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getAllOrders
     * @param {module:com.kodfarki.subscreasy.client/OrderResourceApi~getAllOrdersUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:com.kodfarki.subscreasy.client.model/Order>}
     */
    this.getAllOrdersUsingGET = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apiKey'];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = [Order];

      return this.apiClient.callApi(
        '/api/orders', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getOrderUsingGET operation.
     * @callback module:com.kodfarki.subscreasy.client/OrderResourceApi~getOrderUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:com.kodfarki.subscreasy.client.model/Order} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getOrder
     * @param {Number} id id
     * @param {module:com.kodfarki.subscreasy.client/OrderResourceApi~getOrderUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.kodfarki.subscreasy.client.model/Order}
     */
    this.getOrderUsingGET = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getOrderUsingGET");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apiKey'];
      var contentTypes = [];
      var accepts = ['*/*'];
      var returnType = Order;

      return this.apiClient.callApi(
        '/api/orders/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateOrderUsingPUT operation.
     * @callback module:com.kodfarki.subscreasy.client/OrderResourceApi~updateOrderUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param {module:com.kodfarki.subscreasy.client.model/Order} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * updateOrder
     * @param {module:com.kodfarki.subscreasy.client.model/Order} order order
     * @param {module:com.kodfarki.subscreasy.client/OrderResourceApi~updateOrderUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.kodfarki.subscreasy.client.model/Order}
     */
    this.updateOrderUsingPUT = function(order, callback) {
      var postBody = order;

      // verify the required parameter 'order' is set
      if (order === undefined || order === null) {
        throw new Error("Missing the required parameter 'order' when calling updateOrderUsingPUT");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apiKey'];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = Order;

      return this.apiClient.callApi(
        '/api/orders', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
