/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'com.kodfarki.subscreasy.client.model/LoginVM', 'com.kodfarki.subscreasy.client.model/ResponseEntity'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../com.kodfarki.subscreasy.client.model/LoginVM'), require('../com.kodfarki.subscreasy.client.model/ResponseEntity'));
  } else {
    // Browser globals (root is window)
    if (!root.SubscreasyJsClient) {
      root.SubscreasyJsClient = {};
    }
    root.SubscreasyJsClient.UserJwtControllerApi = factory(root.SubscreasyJsClient.ApiClient, root.SubscreasyJsClient.LoginVM, root.SubscreasyJsClient.ResponseEntity);
  }
}(this, function(ApiClient, LoginVM, ResponseEntity) {
  'use strict';

  /**
   * UserJwtController service.
   * @module com.kodfarki.subscreasy.client/UserJwtControllerApi
   * @version 1.0.0
   */

  /**
   * Constructs a new UserJwtControllerApi. 
   * @alias module:com.kodfarki.subscreasy.client/UserJwtControllerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the authorizeUsingPOST operation.
     * @callback module:com.kodfarki.subscreasy.client/UserJwtControllerApi~authorizeUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:com.kodfarki.subscreasy.client.model/ResponseEntity} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * authorize
     * @param {module:com.kodfarki.subscreasy.client.model/LoginVM} loginVM loginVM
     * @param {module:com.kodfarki.subscreasy.client/UserJwtControllerApi~authorizeUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.kodfarki.subscreasy.client.model/ResponseEntity}
     */
    this.authorizeUsingPOST = function(loginVM, callback) {
      var postBody = loginVM;

      // verify the required parameter 'loginVM' is set
      if (loginVM === undefined || loginVM === null) {
        throw new Error("Missing the required parameter 'loginVM' when calling authorizeUsingPOST");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['apiKey'];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = ResponseEntity;

      return this.apiClient.callApi(
        '/api/authenticate', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
