/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ServiceInstance'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ServiceInstance'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.AuthorizedServicesResponse = factory(root.ApiDocumentation.ApiClient, root.ApiDocumentation.ServiceInstance);
  }
}(this, function(ApiClient, ServiceInstance) {
  'use strict';




  /**
   * The AuthorizedServicesResponse model module.
   * @module model/AuthorizedServicesResponse
   * @version 1.0
   */

  /**
   * Constructs a new <code>AuthorizedServicesResponse</code>.
   * @alias module:model/AuthorizedServicesResponse
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>AuthorizedServicesResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthorizedServicesResponse} obj Optional instance to populate.
   * @return {module:model/AuthorizedServicesResponse} The populated <code>AuthorizedServicesResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('services')) {
        obj['services'] = ApiClient.convertToType(data['services'], [ServiceInstance]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ServiceInstance>} services
   */
  exports.prototype['services'] = undefined;



  return exports;
}));


