/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.RecurrencePeriod = factory(root.ApiDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RecurrencePeriod model module.
   * @module model/RecurrencePeriod
   * @version 1.0
   */

  /**
   * Constructs a new <code>RecurrencePeriod</code>.
   * @alias module:model/RecurrencePeriod
   * @class
   * @param length {Number} 
   * @param recurrenceType {module:model/RecurrencePeriod.RecurrenceTypeEnum} 
   */
  var exports = function(length, recurrenceType) {
    var _this = this;


    _this['length'] = length;
    _this['recurrenceType'] = recurrenceType;
  };

  /**
   * Constructs a <code>RecurrencePeriod</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecurrencePeriod} obj Optional instance to populate.
   * @return {module:model/RecurrencePeriod} The populated <code>RecurrencePeriod</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('length')) {
        obj['length'] = ApiClient.convertToType(data['length'], 'Number');
      }
      if (data.hasOwnProperty('recurrenceType')) {
        obj['recurrenceType'] = ApiClient.convertToType(data['recurrenceType'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} length
   */
  exports.prototype['length'] = undefined;
  /**
   * @member {module:model/RecurrencePeriod.RecurrenceTypeEnum} recurrenceType
   */
  exports.prototype['recurrenceType'] = undefined;


  /**
   * Allowed values for the <code>recurrenceType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RecurrenceTypeEnum = {
    /**
     * value: "SECONDLY"
     * @const
     */
    "SECONDLY": "SECONDLY",
    /**
     * value: "MINUTELY"
     * @const
     */
    "MINUTELY": "MINUTELY",
    /**
     * value: "HOURLY"
     * @const
     */
    "HOURLY": "HOURLY",
    /**
     * value: "DAILY"
     * @const
     */
    "DAILY": "DAILY",
    /**
     * value: "WEEKLY"
     * @const
     */
    "WEEKLY": "WEEKLY",
    /**
     * value: "MONTHLY"
     * @const
     */
    "MONTHLY": "MONTHLY",
    /**
     * value: "YEARLY"
     * @const
     */
    "YEARLY": "YEARLY"  };


  return exports;
}));


