/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.Authorization = factory(root.ApiDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Authorization model module.
   * @module com.kodfarki.subscreasy.client.model/Authorization
   * @version 1.0
   */

  /**
   * Constructs a new <code>Authorization</code>.
   * @alias module:com.kodfarki.subscreasy.client.model/Authorization
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Authorization</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.kodfarki.subscreasy.client.model/Authorization} obj Optional instance to populate.
   * @return {module:com.kodfarki.subscreasy.client.model/Authorization} The populated <code>Authorization</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('serviceId')) {
        obj['serviceId'] = ApiClient.convertToType(data['serviceId'], 'Number');
      }
      if (data.hasOwnProperty('serviceUserId')) {
        obj['serviceUserId'] = ApiClient.convertToType(data['serviceUserId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} serviceId
   */
  exports.prototype['serviceId'] = undefined;
  /**
   * @member {String} serviceUserId
   */
  exports.prototype['serviceUserId'] = undefined;



  return exports;
}));


