/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ServiceInstance from './ServiceInstance';

/**
 * The AuthorizedServicesResponse model module.
 * @module com.kodfarki.subscreasy.client.model/AuthorizedServicesResponse
 * @version 1.0.0
 */
class AuthorizedServicesResponse {
    /**
     * Constructs a new <code>AuthorizedServicesResponse</code>.
     * @alias module:com.kodfarki.subscreasy.client.model/AuthorizedServicesResponse
     */
    constructor() { 
        
        AuthorizedServicesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthorizedServicesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.kodfarki.subscreasy.client.model/AuthorizedServicesResponse} obj Optional instance to populate.
     * @return {module:com.kodfarki.subscreasy.client.model/AuthorizedServicesResponse} The populated <code>AuthorizedServicesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthorizedServicesResponse();

            if (data.hasOwnProperty('services')) {
                obj['services'] = ApiClient.convertToType(data['services'], [ServiceInstance]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:com.kodfarki.subscreasy.client.model/ServiceInstance>} services
 */
AuthorizedServicesResponse.prototype['services'] = undefined;






export default AuthorizedServicesResponse;

