/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Cancellation model module.
 * @module com.kodfarki.subscreasy.client.model/Cancellation
 * @version 1.0.0
 */
class Cancellation {
    /**
     * Constructs a new <code>Cancellation</code>.
     * @alias module:com.kodfarki.subscreasy.client.model/Cancellation
     */
    constructor() { 
        
        Cancellation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Cancellation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.kodfarki.subscreasy.client.model/Cancellation} obj Optional instance to populate.
     * @return {module:com.kodfarki.subscreasy.client.model/Cancellation} The populated <code>Cancellation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Cancellation();

            if (data.hasOwnProperty('cancellationType')) {
                obj['cancellationType'] = ApiClient.convertToType(data['cancellationType'], 'String');
            }
            if (data.hasOwnProperty('subscriberId')) {
                obj['subscriberId'] = ApiClient.convertToType(data['subscriberId'], 'Number');
            }
            if (data.hasOwnProperty('subscriptionId')) {
                obj['subscriptionId'] = ApiClient.convertToType(data['subscriptionId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:com.kodfarki.subscreasy.client.model/Cancellation.CancellationTypeEnum} cancellationType
 */
Cancellation.prototype['cancellationType'] = undefined;

/**
 * @member {Number} subscriberId
 */
Cancellation.prototype['subscriberId'] = undefined;

/**
 * @member {Number} subscriptionId
 */
Cancellation.prototype['subscriptionId'] = undefined;





/**
 * Allowed values for the <code>cancellationType</code> property.
 * @enum {String}
 * @readonly
 */
Cancellation['CancellationTypeEnum'] = {

    /**
     * value: "IMMEDIATE"
     * @const
     */
    "IMMEDIATE": "IMMEDIATE",

    /**
     * value: "ENDOFTHEPERIOD"
     * @const
     */
    "ENDOFTHEPERIOD": "ENDOFTHEPERIOD"
};



export default Cancellation;

