/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SavedCard from './SavedCard';

/**
 * The ChargingLog model module.
 * @module com.kodfarki.subscreasy.client.model/ChargingLog
 * @version 1.0.0
 */
class ChargingLog {
    /**
     * Constructs a new <code>ChargingLog</code>.
     * @alias module:com.kodfarki.subscreasy.client.model/ChargingLog
     */
    constructor() { 
        
        ChargingLog.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChargingLog</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.kodfarki.subscreasy.client.model/ChargingLog} obj Optional instance to populate.
     * @return {module:com.kodfarki.subscreasy.client.model/ChargingLog} The populated <code>ChargingLog</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChargingLog();

            if (data.hasOwnProperty('appliedCoupon')) {
                obj['appliedCoupon'] = ApiClient.convertToType(data['appliedCoupon'], 'Number');
            }
            if (data.hasOwnProperty('authCode')) {
                obj['authCode'] = ApiClient.convertToType(data['authCode'], 'String');
            }
            if (data.hasOwnProperty('companyId')) {
                obj['companyId'] = ApiClient.convertToType(data['companyId'], 'Number');
            }
            if (data.hasOwnProperty('createDate')) {
                obj['createDate'] = ApiClient.convertToType(data['createDate'], 'Date');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('errorCode')) {
                obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'String');
            }
            if (data.hasOwnProperty('errorText')) {
                obj['errorText'] = ApiClient.convertToType(data['errorText'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('invoiceId')) {
                obj['invoiceId'] = ApiClient.convertToType(data['invoiceId'], 'Number');
            }
            if (data.hasOwnProperty('jobId')) {
                obj['jobId'] = ApiClient.convertToType(data['jobId'], 'Number');
            }
            if (data.hasOwnProperty('offerId')) {
                obj['offerId'] = ApiClient.convertToType(data['offerId'], 'Number');
            }
            if (data.hasOwnProperty('parentId')) {
                obj['parentId'] = ApiClient.convertToType(data['parentId'], 'Number');
            }
            if (data.hasOwnProperty('paymentGateway')) {
                obj['paymentGateway'] = ApiClient.convertToType(data['paymentGateway'], 'String');
            }
            if (data.hasOwnProperty('paymentId')) {
                obj['paymentId'] = ApiClient.convertToType(data['paymentId'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('refundDate')) {
                obj['refundDate'] = ApiClient.convertToType(data['refundDate'], 'Date');
            }
            if (data.hasOwnProperty('savedCard')) {
                obj['savedCard'] = SavedCard.constructFromObject(data['savedCard']);
            }
            if (data.hasOwnProperty('savedCardId')) {
                obj['savedCardId'] = ApiClient.convertToType(data['savedCardId'], 'Number');
            }
            if (data.hasOwnProperty('serviceInstanceId')) {
                obj['serviceInstanceId'] = ApiClient.convertToType(data['serviceInstanceId'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('subscriberId')) {
                obj['subscriberId'] = ApiClient.convertToType(data['subscriberId'], 'Number');
            }
            if (data.hasOwnProperty('subscriberSecureId')) {
                obj['subscriberSecureId'] = ApiClient.convertToType(data['subscriberSecureId'], 'String');
            }
            if (data.hasOwnProperty('subscriptionId')) {
                obj['subscriptionId'] = ApiClient.convertToType(data['subscriptionId'], 'Number');
            }
            if (data.hasOwnProperty('threeds')) {
                obj['threeds'] = ApiClient.convertToType(data['threeds'], 'Boolean');
            }
            if (data.hasOwnProperty('transactionId')) {
                obj['transactionId'] = ApiClient.convertToType(data['transactionId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} appliedCoupon
 */
ChargingLog.prototype['appliedCoupon'] = undefined;

/**
 * @member {String} authCode
 */
ChargingLog.prototype['authCode'] = undefined;

/**
 * @member {Number} companyId
 */
ChargingLog.prototype['companyId'] = undefined;

/**
 * @member {Date} createDate
 */
ChargingLog.prototype['createDate'] = undefined;

/**
 * @member {String} currency
 */
ChargingLog.prototype['currency'] = undefined;

/**
 * @member {String} errorCode
 */
ChargingLog.prototype['errorCode'] = undefined;

/**
 * @member {String} errorText
 */
ChargingLog.prototype['errorText'] = undefined;

/**
 * @member {Number} id
 */
ChargingLog.prototype['id'] = undefined;

/**
 * @member {Number} invoiceId
 */
ChargingLog.prototype['invoiceId'] = undefined;

/**
 * @member {Number} jobId
 */
ChargingLog.prototype['jobId'] = undefined;

/**
 * @member {Number} offerId
 */
ChargingLog.prototype['offerId'] = undefined;

/**
 * @member {Number} parentId
 */
ChargingLog.prototype['parentId'] = undefined;

/**
 * @member {module:com.kodfarki.subscreasy.client.model/ChargingLog.PaymentGatewayEnum} paymentGateway
 */
ChargingLog.prototype['paymentGateway'] = undefined;

/**
 * @member {String} paymentId
 */
ChargingLog.prototype['paymentId'] = undefined;

/**
 * @member {Number} price
 */
ChargingLog.prototype['price'] = undefined;

/**
 * @member {module:com.kodfarki.subscreasy.client.model/ChargingLog.ReasonEnum} reason
 */
ChargingLog.prototype['reason'] = undefined;

/**
 * @member {Date} refundDate
 */
ChargingLog.prototype['refundDate'] = undefined;

/**
 * @member {module:com.kodfarki.subscreasy.client.model/SavedCard} savedCard
 */
ChargingLog.prototype['savedCard'] = undefined;

/**
 * @member {Number} savedCardId
 */
ChargingLog.prototype['savedCardId'] = undefined;

/**
 * @member {Number} serviceInstanceId
 */
ChargingLog.prototype['serviceInstanceId'] = undefined;

/**
 * @member {module:com.kodfarki.subscreasy.client.model/ChargingLog.StatusEnum} status
 */
ChargingLog.prototype['status'] = undefined;

/**
 * @member {Number} subscriberId
 */
ChargingLog.prototype['subscriberId'] = undefined;

/**
 * @member {String} subscriberSecureId
 */
ChargingLog.prototype['subscriberSecureId'] = undefined;

/**
 * @member {Number} subscriptionId
 */
ChargingLog.prototype['subscriptionId'] = undefined;

/**
 * @member {Boolean} threeds
 */
ChargingLog.prototype['threeds'] = undefined;

/**
 * @member {String} transactionId
 */
ChargingLog.prototype['transactionId'] = undefined;





/**
 * Allowed values for the <code>paymentGateway</code> property.
 * @enum {String}
 * @readonly
 */
ChargingLog['PaymentGatewayEnum'] = {

    /**
     * value: "OFFLINE"
     * @const
     */
    "OFFLINE": "OFFLINE",

    /**
     * value: "IYZICO"
     * @const
     */
    "IYZICO": "IYZICO",

    /**
     * value: "PAYU"
     * @const
     */
    "PAYU": "PAYU",

    /**
     * value: "PAYTR"
     * @const
     */
    "PAYTR": "PAYTR",

    /**
     * value: "MOBILEXPRESS"
     * @const
     */
    "MOBILEXPRESS": "MOBILEXPRESS",

    /**
     * value: "AKTIFBANK"
     * @const
     */
    "AKTIFBANK": "AKTIFBANK"
};


/**
 * Allowed values for the <code>reason</code> property.
 * @enum {String}
 * @readonly
 */
ChargingLog['ReasonEnum'] = {

    /**
     * value: "START"
     * @const
     */
    "START": "START",

    /**
     * value: "RENEWAL"
     * @const
     */
    "RENEWAL": "RENEWAL",

    /**
     * value: "OVER_USAGE"
     * @const
     */
    "OVER_USAGE": "OVER_USAGE",

    /**
     * value: "REFUND"
     * @const
     */
    "REFUND": "REFUND",

    /**
     * value: "SAVE_CARD"
     * @const
     */
    "SAVE_CARD": "SAVE_CARD",

    /**
     * value: "TRIAL_PERIOD"
     * @const
     */
    "TRIAL_PERIOD": "TRIAL_PERIOD",

    /**
     * value: "PAYMENT"
     * @const
     */
    "PAYMENT": "PAYMENT"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
ChargingLog['StatusEnum'] = {

    /**
     * value: "NOT_PAID"
     * @const
     */
    "NOT_PAID": "NOT_PAID",

    /**
     * value: "PAID"
     * @const
     */
    "PAID": "PAID",

    /**
     * value: "FAIL"
     * @const
     */
    "FAIL": "FAIL",

    /**
     * value: "REFUNDED"
     * @const
     */
    "REFUNDED": "REFUNDED"
};



export default ChargingLog;

