/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Company from './Company';

/**
 * The CompanyProps model module.
 * @module com.kodfarki.subscreasy.client.model/CompanyProps
 * @version 1.0.0
 */
class CompanyProps {
    /**
     * Constructs a new <code>CompanyProps</code>.
     * @alias module:com.kodfarki.subscreasy.client.model/CompanyProps
     * @param billingInformationMandatory {Boolean} 
     * @param branding {Boolean} 
     * @param domainName {String} 
     * @param notifyNewSubscription {Boolean} 
     * @param notifyRenewal {Boolean} 
     * @param notifySubscriptionCancellation {Boolean} 
     */
    constructor(billingInformationMandatory, branding, domainName, notifyNewSubscription, notifyRenewal, notifySubscriptionCancellation) { 
        
        CompanyProps.initialize(this, billingInformationMandatory, branding, domainName, notifyNewSubscription, notifyRenewal, notifySubscriptionCancellation);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, billingInformationMandatory, branding, domainName, notifyNewSubscription, notifyRenewal, notifySubscriptionCancellation) { 
        obj['billingInformationMandatory'] = billingInformationMandatory;
        obj['branding'] = branding;
        obj['domainName'] = domainName;
        obj['notifyNewSubscription'] = notifyNewSubscription;
        obj['notifyRenewal'] = notifyRenewal;
        obj['notifySubscriptionCancellation'] = notifySubscriptionCancellation;
    }

    /**
     * Constructs a <code>CompanyProps</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.kodfarki.subscreasy.client.model/CompanyProps} obj Optional instance to populate.
     * @return {module:com.kodfarki.subscreasy.client.model/CompanyProps} The populated <code>CompanyProps</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompanyProps();

            if (data.hasOwnProperty('aktifbankClientId')) {
                obj['aktifbankClientId'] = ApiClient.convertToType(data['aktifbankClientId'], 'Number');
            }
            if (data.hasOwnProperty('aktifbankClientIdForSaveCard')) {
                obj['aktifbankClientIdForSaveCard'] = ApiClient.convertToType(data['aktifbankClientIdForSaveCard'], 'Number');
            }
            if (data.hasOwnProperty('aktifbankEncryptionKey')) {
                obj['aktifbankEncryptionKey'] = ApiClient.convertToType(data['aktifbankEncryptionKey'], 'String');
            }
            if (data.hasOwnProperty('aktifbankName')) {
                obj['aktifbankName'] = ApiClient.convertToType(data['aktifbankName'], 'String');
            }
            if (data.hasOwnProperty('aktifbankNameForSaveCard')) {
                obj['aktifbankNameForSaveCard'] = ApiClient.convertToType(data['aktifbankNameForSaveCard'], 'String');
            }
            if (data.hasOwnProperty('aktifbankPassword')) {
                obj['aktifbankPassword'] = ApiClient.convertToType(data['aktifbankPassword'], 'String');
            }
            if (data.hasOwnProperty('aktifbankPasswordForSaveCard')) {
                obj['aktifbankPasswordForSaveCard'] = ApiClient.convertToType(data['aktifbankPasswordForSaveCard'], 'String');
            }
            if (data.hasOwnProperty('billingDate')) {
                obj['billingDate'] = ApiClient.convertToType(data['billingDate'], 'Number');
            }
            if (data.hasOwnProperty('billingInformationMandatory')) {
                obj['billingInformationMandatory'] = ApiClient.convertToType(data['billingInformationMandatory'], 'Boolean');
            }
            if (data.hasOwnProperty('billingThresholdDays')) {
                obj['billingThresholdDays'] = ApiClient.convertToType(data['billingThresholdDays'], 'Number');
            }
            if (data.hasOwnProperty('branding')) {
                obj['branding'] = ApiClient.convertToType(data['branding'], 'Boolean');
            }
            if (data.hasOwnProperty('callbackUrl')) {
                obj['callbackUrl'] = ApiClient.convertToType(data['callbackUrl'], 'String');
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = Company.constructFromObject(data['company']);
            }
            if (data.hasOwnProperty('contactEmail')) {
                obj['contactEmail'] = ApiClient.convertToType(data['contactEmail'], 'String');
            }
            if (data.hasOwnProperty('domainName')) {
                obj['domainName'] = ApiClient.convertToType(data['domainName'], 'String');
            }
            if (data.hasOwnProperty('hostedPageCSSPath')) {
                obj['hostedPageCSSPath'] = ApiClient.convertToType(data['hostedPageCSSPath'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('logoPath')) {
                obj['logoPath'] = ApiClient.convertToType(data['logoPath'], 'String');
            }
            if (data.hasOwnProperty('mobilExpressApiPassword')) {
                obj['mobilExpressApiPassword'] = ApiClient.convertToType(data['mobilExpressApiPassword'], 'String');
            }
            if (data.hasOwnProperty('mobilExpressMerchantKey')) {
                obj['mobilExpressMerchantKey'] = ApiClient.convertToType(data['mobilExpressMerchantKey'], 'String');
            }
            if (data.hasOwnProperty('mobilExpressPosid')) {
                obj['mobilExpressPosid'] = ApiClient.convertToType(data['mobilExpressPosid'], 'Number');
            }
            if (data.hasOwnProperty('mobilePaymentGateway')) {
                obj['mobilePaymentGateway'] = ApiClient.convertToType(data['mobilePaymentGateway'], 'String');
            }
            if (data.hasOwnProperty('notifyNewSubscription')) {
                obj['notifyNewSubscription'] = ApiClient.convertToType(data['notifyNewSubscription'], 'Boolean');
            }
            if (data.hasOwnProperty('notifyRenewal')) {
                obj['notifyRenewal'] = ApiClient.convertToType(data['notifyRenewal'], 'Boolean');
            }
            if (data.hasOwnProperty('notifySubscriptionCancellation')) {
                obj['notifySubscriptionCancellation'] = ApiClient.convertToType(data['notifySubscriptionCancellation'], 'Boolean');
            }
            if (data.hasOwnProperty('paymentGateway')) {
                obj['paymentGateway'] = ApiClient.convertToType(data['paymentGateway'], 'String');
            }
            if (data.hasOwnProperty('paymentGatewayApiKey')) {
                obj['paymentGatewayApiKey'] = ApiClient.convertToType(data['paymentGatewayApiKey'], 'String');
            }
            if (data.hasOwnProperty('paymentGatewaySecurityKey')) {
                obj['paymentGatewaySecurityKey'] = ApiClient.convertToType(data['paymentGatewaySecurityKey'], 'String');
            }
            if (data.hasOwnProperty('paytrDirectApiEnabled')) {
                obj['paytrDirectApiEnabled'] = ApiClient.convertToType(data['paytrDirectApiEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('paytrMerchantId')) {
                obj['paytrMerchantId'] = ApiClient.convertToType(data['paytrMerchantId'], 'Number');
            }
            if (data.hasOwnProperty('payuMerchantKeyRenewals')) {
                obj['payuMerchantKeyRenewals'] = ApiClient.convertToType(data['payuMerchantKeyRenewals'], 'String');
            }
            if (data.hasOwnProperty('payuSecretKeyRenewals')) {
                obj['payuSecretKeyRenewals'] = ApiClient.convertToType(data['payuSecretKeyRenewals'], 'String');
            }
            if (data.hasOwnProperty('privacyPolicyUrl')) {
                obj['privacyPolicyUrl'] = ApiClient.convertToType(data['privacyPolicyUrl'], 'String');
            }
            if (data.hasOwnProperty('retryCount')) {
                obj['retryCount'] = ApiClient.convertToType(data['retryCount'], 'Number');
            }
            if (data.hasOwnProperty('retryPeriod')) {
                obj['retryPeriod'] = ApiClient.convertToType(data['retryPeriod'], 'Number');
            }
            if (data.hasOwnProperty('sendDailyReports')) {
                obj['sendDailyReports'] = ApiClient.convertToType(data['sendDailyReports'], 'String');
            }
            if (data.hasOwnProperty('subscreasyApiKey')) {
                obj['subscreasyApiKey'] = ApiClient.convertToType(data['subscreasyApiKey'], 'String');
            }
            if (data.hasOwnProperty('subscreasySecureKey')) {
                obj['subscreasySecureKey'] = ApiClient.convertToType(data['subscreasySecureKey'], 'String');
            }
            if (data.hasOwnProperty('wirecardErrorMessage')) {
                obj['wirecardErrorMessage'] = ApiClient.convertToType(data['wirecardErrorMessage'], 'String');
            }
            if (data.hasOwnProperty('wirecardPin')) {
                obj['wirecardPin'] = ApiClient.convertToType(data['wirecardPin'], 'String');
            }
            if (data.hasOwnProperty('wirecardSuccessfulMessage')) {
                obj['wirecardSuccessfulMessage'] = ApiClient.convertToType(data['wirecardSuccessfulMessage'], 'String');
            }
            if (data.hasOwnProperty('wirecardTurkcellServisId')) {
                obj['wirecardTurkcellServisId'] = ApiClient.convertToType(data['wirecardTurkcellServisId'], 'String');
            }
            if (data.hasOwnProperty('wirecardUserCode')) {
                obj['wirecardUserCode'] = ApiClient.convertToType(data['wirecardUserCode'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} aktifbankClientId
 */
CompanyProps.prototype['aktifbankClientId'] = undefined;

/**
 * @member {Number} aktifbankClientIdForSaveCard
 */
CompanyProps.prototype['aktifbankClientIdForSaveCard'] = undefined;

/**
 * @member {String} aktifbankEncryptionKey
 */
CompanyProps.prototype['aktifbankEncryptionKey'] = undefined;

/**
 * @member {String} aktifbankName
 */
CompanyProps.prototype['aktifbankName'] = undefined;

/**
 * @member {String} aktifbankNameForSaveCard
 */
CompanyProps.prototype['aktifbankNameForSaveCard'] = undefined;

/**
 * @member {String} aktifbankPassword
 */
CompanyProps.prototype['aktifbankPassword'] = undefined;

/**
 * @member {String} aktifbankPasswordForSaveCard
 */
CompanyProps.prototype['aktifbankPasswordForSaveCard'] = undefined;

/**
 * @member {Number} billingDate
 */
CompanyProps.prototype['billingDate'] = undefined;

/**
 * @member {Boolean} billingInformationMandatory
 */
CompanyProps.prototype['billingInformationMandatory'] = undefined;

/**
 * @member {Number} billingThresholdDays
 */
CompanyProps.prototype['billingThresholdDays'] = undefined;

/**
 * @member {Boolean} branding
 */
CompanyProps.prototype['branding'] = undefined;

/**
 * @member {String} callbackUrl
 */
CompanyProps.prototype['callbackUrl'] = undefined;

/**
 * @member {module:com.kodfarki.subscreasy.client.model/Company} company
 */
CompanyProps.prototype['company'] = undefined;

/**
 * @member {String} contactEmail
 */
CompanyProps.prototype['contactEmail'] = undefined;

/**
 * @member {String} domainName
 */
CompanyProps.prototype['domainName'] = undefined;

/**
 * @member {String} hostedPageCSSPath
 */
CompanyProps.prototype['hostedPageCSSPath'] = undefined;

/**
 * @member {Number} id
 */
CompanyProps.prototype['id'] = undefined;

/**
 * @member {String} logoPath
 */
CompanyProps.prototype['logoPath'] = undefined;

/**
 * @member {String} mobilExpressApiPassword
 */
CompanyProps.prototype['mobilExpressApiPassword'] = undefined;

/**
 * @member {String} mobilExpressMerchantKey
 */
CompanyProps.prototype['mobilExpressMerchantKey'] = undefined;

/**
 * @member {Number} mobilExpressPosid
 */
CompanyProps.prototype['mobilExpressPosid'] = undefined;

/**
 * @member {module:com.kodfarki.subscreasy.client.model/CompanyProps.MobilePaymentGatewayEnum} mobilePaymentGateway
 */
CompanyProps.prototype['mobilePaymentGateway'] = undefined;

/**
 * @member {Boolean} notifyNewSubscription
 */
CompanyProps.prototype['notifyNewSubscription'] = undefined;

/**
 * @member {Boolean} notifyRenewal
 */
CompanyProps.prototype['notifyRenewal'] = undefined;

/**
 * @member {Boolean} notifySubscriptionCancellation
 */
CompanyProps.prototype['notifySubscriptionCancellation'] = undefined;

/**
 * @member {module:com.kodfarki.subscreasy.client.model/CompanyProps.PaymentGatewayEnum} paymentGateway
 */
CompanyProps.prototype['paymentGateway'] = undefined;

/**
 * @member {String} paymentGatewayApiKey
 */
CompanyProps.prototype['paymentGatewayApiKey'] = undefined;

/**
 * @member {String} paymentGatewaySecurityKey
 */
CompanyProps.prototype['paymentGatewaySecurityKey'] = undefined;

/**
 * @member {Boolean} paytrDirectApiEnabled
 */
CompanyProps.prototype['paytrDirectApiEnabled'] = undefined;

/**
 * @member {Number} paytrMerchantId
 */
CompanyProps.prototype['paytrMerchantId'] = undefined;

/**
 * @member {String} payuMerchantKeyRenewals
 */
CompanyProps.prototype['payuMerchantKeyRenewals'] = undefined;

/**
 * @member {String} payuSecretKeyRenewals
 */
CompanyProps.prototype['payuSecretKeyRenewals'] = undefined;

/**
 * @member {String} privacyPolicyUrl
 */
CompanyProps.prototype['privacyPolicyUrl'] = undefined;

/**
 * @member {Number} retryCount
 */
CompanyProps.prototype['retryCount'] = undefined;

/**
 * @member {Number} retryPeriod
 */
CompanyProps.prototype['retryPeriod'] = undefined;

/**
 * @member {String} sendDailyReports
 */
CompanyProps.prototype['sendDailyReports'] = undefined;

/**
 * @member {String} subscreasyApiKey
 */
CompanyProps.prototype['subscreasyApiKey'] = undefined;

/**
 * @member {String} subscreasySecureKey
 */
CompanyProps.prototype['subscreasySecureKey'] = undefined;

/**
 * @member {String} wirecardErrorMessage
 */
CompanyProps.prototype['wirecardErrorMessage'] = undefined;

/**
 * @member {String} wirecardPin
 */
CompanyProps.prototype['wirecardPin'] = undefined;

/**
 * @member {String} wirecardSuccessfulMessage
 */
CompanyProps.prototype['wirecardSuccessfulMessage'] = undefined;

/**
 * @member {String} wirecardTurkcellServisId
 */
CompanyProps.prototype['wirecardTurkcellServisId'] = undefined;

/**
 * @member {String} wirecardUserCode
 */
CompanyProps.prototype['wirecardUserCode'] = undefined;





/**
 * Allowed values for the <code>mobilePaymentGateway</code> property.
 * @enum {String}
 * @readonly
 */
CompanyProps['MobilePaymentGatewayEnum'] = {

    /**
     * value: "DISABLED"
     * @const
     */
    "DISABLED": "DISABLED",

    /**
     * value: "WIRECARD"
     * @const
     */
    "WIRECARD": "WIRECARD"
};


/**
 * Allowed values for the <code>paymentGateway</code> property.
 * @enum {String}
 * @readonly
 */
CompanyProps['PaymentGatewayEnum'] = {

    /**
     * value: "OFFLINE"
     * @const
     */
    "OFFLINE": "OFFLINE",

    /**
     * value: "IYZICO"
     * @const
     */
    "IYZICO": "IYZICO",

    /**
     * value: "PAYU"
     * @const
     */
    "PAYU": "PAYU",

    /**
     * value: "PAYTR"
     * @const
     */
    "PAYTR": "PAYTR",

    /**
     * value: "MOBILEXPRESS"
     * @const
     */
    "MOBILEXPRESS": "MOBILEXPRESS",

    /**
     * value: "AKTIFBANK"
     * @const
     */
    "AKTIFBANK": "AKTIFBANK"
};



export default CompanyProps;

