/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SubscreasyJsClient) {
      root.SubscreasyJsClient = {};
    }
    root.SubscreasyJsClient.Deduction = factory(root.SubscreasyJsClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Deduction model module.
   * @module com.kodfarki.subscreasy.client.model/Deduction
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Deduction</code>.
   * @alias module:com.kodfarki.subscreasy.client.model/Deduction
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>Deduction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.kodfarki.subscreasy.client.model/Deduction} obj Optional instance to populate.
   * @return {module:com.kodfarki.subscreasy.client.model/Deduction} The populated <code>Deduction</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('serviceId')) {
        obj['serviceId'] = ApiClient.convertToType(data['serviceId'], 'Number');
      }
      if (data.hasOwnProperty('usageEndTime')) {
        obj['usageEndTime'] = ApiClient.convertToType(data['usageEndTime'], 'Date');
      }
      if (data.hasOwnProperty('usageStartTime')) {
        obj['usageStartTime'] = ApiClient.convertToType(data['usageStartTime'], 'Date');
      }
      if (data.hasOwnProperty('userId')) {
        obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} serviceId
   */
  exports.prototype['serviceId'] = undefined;
  /**
   * @member {Date} usageEndTime
   */
  exports.prototype['usageEndTime'] = undefined;
  /**
   * @member {Date} usageStartTime
   */
  exports.prototype['usageStartTime'] = undefined;
  /**
   * @member {String} userId
   */
  exports.prototype['userId'] = undefined;



  return exports;
}));


