/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeductionResult model module.
 * @module com.kodfarki.subscreasy.client.model/DeductionResult
 * @version 1.0.0
 */
class DeductionResult {
    /**
     * Constructs a new <code>DeductionResult</code>.
     * @alias module:com.kodfarki.subscreasy.client.model/DeductionResult
     */
    constructor() { 
        
        DeductionResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeductionResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.kodfarki.subscreasy.client.model/DeductionResult} obj Optional instance to populate.
     * @return {module:com.kodfarki.subscreasy.client.model/DeductionResult} The populated <code>DeductionResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeductionResult();

            if (data.hasOwnProperty('capacity')) {
                obj['capacity'] = ApiClient.convertToType(data['capacity'], 'Number');
            }
            if (data.hasOwnProperty('consumedResourceId')) {
                obj['consumedResourceId'] = ApiClient.convertToType(data['consumedResourceId'], 'Number');
            }
            if (data.hasOwnProperty('overUsage')) {
                obj['overUsage'] = ApiClient.convertToType(data['overUsage'], 'Number');
            }
            if (data.hasOwnProperty('requestedAmount')) {
                obj['requestedAmount'] = ApiClient.convertToType(data['requestedAmount'], 'Number');
            }
            if (data.hasOwnProperty('subscriptionId')) {
                obj['subscriptionId'] = ApiClient.convertToType(data['subscriptionId'], 'Number');
            }
            if (data.hasOwnProperty('usage')) {
                obj['usage'] = ApiClient.convertToType(data['usage'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} capacity
 */
DeductionResult.prototype['capacity'] = undefined;

/**
 * @member {Number} consumedResourceId
 */
DeductionResult.prototype['consumedResourceId'] = undefined;

/**
 * @member {Number} overUsage
 */
DeductionResult.prototype['overUsage'] = undefined;

/**
 * @member {Number} requestedAmount
 */
DeductionResult.prototype['requestedAmount'] = undefined;

/**
 * @member {Number} subscriptionId
 */
DeductionResult.prototype['subscriptionId'] = undefined;

/**
 * @member {Number} usage
 */
DeductionResult.prototype['usage'] = undefined;






export default DeductionResult;

