/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Company from './Company';

/**
 * The ManagedUserVM model module.
 * @module com.kodfarki.subscreasy.client.model/ManagedUserVM
 * @version 1.0.0
 */
class ManagedUserVM {
    /**
     * Constructs a new <code>ManagedUserVM</code>.
     * @alias module:com.kodfarki.subscreasy.client.model/ManagedUserVM
     * @param login {String} 
     */
    constructor(login) { 
        
        ManagedUserVM.initialize(this, login);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, login) { 
        obj['login'] = login;
    }

    /**
     * Constructs a <code>ManagedUserVM</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.kodfarki.subscreasy.client.model/ManagedUserVM} obj Optional instance to populate.
     * @return {module:com.kodfarki.subscreasy.client.model/ManagedUserVM} The populated <code>ManagedUserVM</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ManagedUserVM();

            if (data.hasOwnProperty('activated')) {
                obj['activated'] = ApiClient.convertToType(data['activated'], 'Boolean');
            }
            if (data.hasOwnProperty('authorities')) {
                obj['authorities'] = ApiClient.convertToType(data['authorities'], ['String']);
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = Company.constructFromObject(data['company']);
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
            }
            if (data.hasOwnProperty('createdDate')) {
                obj['createdDate'] = ApiClient.convertToType(data['createdDate'], 'Date');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('imageUrl')) {
                obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
            }
            if (data.hasOwnProperty('langKey')) {
                obj['langKey'] = ApiClient.convertToType(data['langKey'], 'String');
            }
            if (data.hasOwnProperty('lastModifiedBy')) {
                obj['lastModifiedBy'] = ApiClient.convertToType(data['lastModifiedBy'], 'String');
            }
            if (data.hasOwnProperty('lastModifiedDate')) {
                obj['lastModifiedDate'] = ApiClient.convertToType(data['lastModifiedDate'], 'Date');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('login')) {
                obj['login'] = ApiClient.convertToType(data['login'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('resetDate')) {
                obj['resetDate'] = ApiClient.convertToType(data['resetDate'], 'String');
            }
            if (data.hasOwnProperty('siteName')) {
                obj['siteName'] = ApiClient.convertToType(data['siteName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} activated
 */
ManagedUserVM.prototype['activated'] = undefined;

/**
 * @member {Array.<String>} authorities
 */
ManagedUserVM.prototype['authorities'] = undefined;

/**
 * @member {module:com.kodfarki.subscreasy.client.model/Company} company
 */
ManagedUserVM.prototype['company'] = undefined;

/**
 * @member {String} createdBy
 */
ManagedUserVM.prototype['createdBy'] = undefined;

/**
 * @member {Date} createdDate
 */
ManagedUserVM.prototype['createdDate'] = undefined;

/**
 * @member {String} email
 */
ManagedUserVM.prototype['email'] = undefined;

/**
 * @member {String} firstName
 */
ManagedUserVM.prototype['firstName'] = undefined;

/**
 * @member {Number} id
 */
ManagedUserVM.prototype['id'] = undefined;

/**
 * @member {String} imageUrl
 */
ManagedUserVM.prototype['imageUrl'] = undefined;

/**
 * @member {String} langKey
 */
ManagedUserVM.prototype['langKey'] = undefined;

/**
 * @member {String} lastModifiedBy
 */
ManagedUserVM.prototype['lastModifiedBy'] = undefined;

/**
 * @member {Date} lastModifiedDate
 */
ManagedUserVM.prototype['lastModifiedDate'] = undefined;

/**
 * @member {String} lastName
 */
ManagedUserVM.prototype['lastName'] = undefined;

/**
 * @member {String} login
 */
ManagedUserVM.prototype['login'] = undefined;

/**
 * @member {String} password
 */
ManagedUserVM.prototype['password'] = undefined;

/**
 * @member {String} resetDate
 */
ManagedUserVM.prototype['resetDate'] = undefined;

/**
 * @member {String} siteName
 */
ManagedUserVM.prototype['siteName'] = undefined;






export default ManagedUserVM;

