/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentCard model module.
 * @module com.kodfarki.subscreasy.client.model/PaymentCard
 * @version 1.0.0
 */
class PaymentCard {
    /**
     * Constructs a new <code>PaymentCard</code>.
     * @alias module:com.kodfarki.subscreasy.client.model/PaymentCard
     */
    constructor() { 
        
        PaymentCard.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentCard</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.kodfarki.subscreasy.client.model/PaymentCard} obj Optional instance to populate.
     * @return {module:com.kodfarki.subscreasy.client.model/PaymentCard} The populated <code>PaymentCard</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentCard();

            if (data.hasOwnProperty('cardAlias')) {
                obj['cardAlias'] = ApiClient.convertToType(data['cardAlias'], 'String');
            }
            if (data.hasOwnProperty('cardExpiry')) {
                obj['cardExpiry'] = ApiClient.convertToType(data['cardExpiry'], 'String');
            }
            if (data.hasOwnProperty('cardFamily')) {
                obj['cardFamily'] = ApiClient.convertToType(data['cardFamily'], 'String');
            }
            if (data.hasOwnProperty('cardHolderName')) {
                obj['cardHolderName'] = ApiClient.convertToType(data['cardHolderName'], 'String');
            }
            if (data.hasOwnProperty('cardNumber')) {
                obj['cardNumber'] = ApiClient.convertToType(data['cardNumber'], 'String');
            }
            if (data.hasOwnProperty('cardToken')) {
                obj['cardToken'] = ApiClient.convertToType(data['cardToken'], 'String');
            }
            if (data.hasOwnProperty('cardUserKey')) {
                obj['cardUserKey'] = ApiClient.convertToType(data['cardUserKey'], 'String');
            }
            if (data.hasOwnProperty('cvc')) {
                obj['cvc'] = ApiClient.convertToType(data['cvc'], 'String');
            }
            if (data.hasOwnProperty('expireMonth')) {
                obj['expireMonth'] = ApiClient.convertToType(data['expireMonth'], 'String');
            }
            if (data.hasOwnProperty('expireYear')) {
                obj['expireYear'] = ApiClient.convertToType(data['expireYear'], 'String');
            }
            if (data.hasOwnProperty('expireYearLast2Digits')) {
                obj['expireYearLast2Digits'] = ApiClient.convertToType(data['expireYearLast2Digits'], 'String');
            }
            if (data.hasOwnProperty('registerCard')) {
                obj['registerCard'] = ApiClient.convertToType(data['registerCard'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} cardAlias
 */
PaymentCard.prototype['cardAlias'] = undefined;

/**
 * @member {String} cardExpiry
 */
PaymentCard.prototype['cardExpiry'] = undefined;

/**
 * @member {String} cardFamily
 */
PaymentCard.prototype['cardFamily'] = undefined;

/**
 * @member {String} cardHolderName
 */
PaymentCard.prototype['cardHolderName'] = undefined;

/**
 * @member {String} cardNumber
 */
PaymentCard.prototype['cardNumber'] = undefined;

/**
 * @member {String} cardToken
 */
PaymentCard.prototype['cardToken'] = undefined;

/**
 * @member {String} cardUserKey
 */
PaymentCard.prototype['cardUserKey'] = undefined;

/**
 * @member {String} cvc
 */
PaymentCard.prototype['cvc'] = undefined;

/**
 * @member {String} expireMonth
 */
PaymentCard.prototype['expireMonth'] = undefined;

/**
 * @member {String} expireYear
 */
PaymentCard.prototype['expireYear'] = undefined;

/**
 * @member {String} expireYearLast2Digits
 */
PaymentCard.prototype['expireYearLast2Digits'] = undefined;

/**
 * @member {Number} registerCard
 */
PaymentCard.prototype['registerCard'] = undefined;






export default PaymentCard;

