/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RecurrencePeriod model module.
 * @module com.kodfarki.subscreasy.client.model/RecurrencePeriod
 * @version 1.0.0
 */
class RecurrencePeriod {
    /**
     * Constructs a new <code>RecurrencePeriod</code>.
     * @alias module:com.kodfarki.subscreasy.client.model/RecurrencePeriod
     * @param length {Number} 
     * @param recurrenceType {module:com.kodfarki.subscreasy.client.model/RecurrencePeriod.RecurrenceTypeEnum} 
     */
    constructor(length, recurrenceType) { 
        
        RecurrencePeriod.initialize(this, length, recurrenceType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, length, recurrenceType) { 
        obj['length'] = length;
        obj['recurrenceType'] = recurrenceType;
    }

    /**
     * Constructs a <code>RecurrencePeriod</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.kodfarki.subscreasy.client.model/RecurrencePeriod} obj Optional instance to populate.
     * @return {module:com.kodfarki.subscreasy.client.model/RecurrencePeriod} The populated <code>RecurrencePeriod</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecurrencePeriod();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('length')) {
                obj['length'] = ApiClient.convertToType(data['length'], 'Number');
            }
            if (data.hasOwnProperty('recurrenceType')) {
                obj['recurrenceType'] = ApiClient.convertToType(data['recurrenceType'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
RecurrencePeriod.prototype['id'] = undefined;

/**
 * @member {Number} length
 */
RecurrencePeriod.prototype['length'] = undefined;

/**
 * @member {module:com.kodfarki.subscreasy.client.model/RecurrencePeriod.RecurrenceTypeEnum} recurrenceType
 */
RecurrencePeriod.prototype['recurrenceType'] = undefined;





/**
 * Allowed values for the <code>recurrenceType</code> property.
 * @enum {String}
 * @readonly
 */
RecurrencePeriod['RecurrenceTypeEnum'] = {

    /**
     * value: "SECONDLY"
     * @const
     */
    "SECONDLY": "SECONDLY",

    /**
     * value: "MINUTELY"
     * @const
     */
    "MINUTELY": "MINUTELY",

    /**
     * value: "HOURLY"
     * @const
     */
    "HOURLY": "HOURLY",

    /**
     * value: "DAILY"
     * @const
     */
    "DAILY": "DAILY",

    /**
     * value: "WEEKLY"
     * @const
     */
    "WEEKLY": "WEEKLY",

    /**
     * value: "MONTHLY"
     * @const
     */
    "MONTHLY": "MONTHLY",

    /**
     * value: "YEARLY"
     * @const
     */
    "YEARLY": "YEARLY"
};



export default RecurrencePeriod;

