/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SavedCard model module.
 * @module com.kodfarki.subscreasy.client.model/SavedCard
 * @version 1.0.0
 */
class SavedCard {
    /**
     * Constructs a new <code>SavedCard</code>.
     * @alias module:com.kodfarki.subscreasy.client.model/SavedCard
     */
    constructor() { 
        
        SavedCard.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SavedCard</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.kodfarki.subscreasy.client.model/SavedCard} obj Optional instance to populate.
     * @return {module:com.kodfarki.subscreasy.client.model/SavedCard} The populated <code>SavedCard</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SavedCard();

            if (data.hasOwnProperty('binNumber')) {
                obj['binNumber'] = ApiClient.convertToType(data['binNumber'], 'String');
            }
            if (data.hasOwnProperty('cardAlias')) {
                obj['cardAlias'] = ApiClient.convertToType(data['cardAlias'], 'String');
            }
            if (data.hasOwnProperty('cardAssociation')) {
                obj['cardAssociation'] = ApiClient.convertToType(data['cardAssociation'], 'String');
            }
            if (data.hasOwnProperty('cardBankCode')) {
                obj['cardBankCode'] = ApiClient.convertToType(data['cardBankCode'], 'Number');
            }
            if (data.hasOwnProperty('cardBankName')) {
                obj['cardBankName'] = ApiClient.convertToType(data['cardBankName'], 'String');
            }
            if (data.hasOwnProperty('cardCVV')) {
                obj['cardCVV'] = ApiClient.convertToType(data['cardCVV'], 'String');
            }
            if (data.hasOwnProperty('cardFamily')) {
                obj['cardFamily'] = ApiClient.convertToType(data['cardFamily'], 'String');
            }
            if (data.hasOwnProperty('cardToken')) {
                obj['cardToken'] = ApiClient.convertToType(data['cardToken'], 'String');
            }
            if (data.hasOwnProperty('cardUserKey')) {
                obj['cardUserKey'] = ApiClient.convertToType(data['cardUserKey'], 'String');
            }
            if (data.hasOwnProperty('cartType')) {
                obj['cartType'] = ApiClient.convertToType(data['cartType'], 'String');
            }
            if (data.hasOwnProperty('companyId')) {
                obj['companyId'] = ApiClient.convertToType(data['companyId'], 'Number');
            }
            if (data.hasOwnProperty('expireDate')) {
                obj['expireDate'] = ApiClient.convertToType(data['expireDate'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('lastFourDigits')) {
                obj['lastFourDigits'] = ApiClient.convertToType(data['lastFourDigits'], 'String');
            }
            if (data.hasOwnProperty('subscriberId')) {
                obj['subscriberId'] = ApiClient.convertToType(data['subscriberId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} binNumber
 */
SavedCard.prototype['binNumber'] = undefined;

/**
 * @member {String} cardAlias
 */
SavedCard.prototype['cardAlias'] = undefined;

/**
 * @member {String} cardAssociation
 */
SavedCard.prototype['cardAssociation'] = undefined;

/**
 * @member {Number} cardBankCode
 */
SavedCard.prototype['cardBankCode'] = undefined;

/**
 * @member {String} cardBankName
 */
SavedCard.prototype['cardBankName'] = undefined;

/**
 * @member {String} cardCVV
 */
SavedCard.prototype['cardCVV'] = undefined;

/**
 * @member {String} cardFamily
 */
SavedCard.prototype['cardFamily'] = undefined;

/**
 * @member {String} cardToken
 */
SavedCard.prototype['cardToken'] = undefined;

/**
 * @member {String} cardUserKey
 */
SavedCard.prototype['cardUserKey'] = undefined;

/**
 * @member {String} cartType
 */
SavedCard.prototype['cartType'] = undefined;

/**
 * @member {Number} companyId
 */
SavedCard.prototype['companyId'] = undefined;

/**
 * @member {Date} expireDate
 */
SavedCard.prototype['expireDate'] = undefined;

/**
 * @member {Number} id
 */
SavedCard.prototype['id'] = undefined;

/**
 * @member {String} lastFourDigits
 */
SavedCard.prototype['lastFourDigits'] = undefined;

/**
 * @member {Number} subscriberId
 */
SavedCard.prototype['subscriberId'] = undefined;






export default SavedCard;

