/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.SavedCard = factory(root.ApiDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SavedCard model module.
   * @module com.kodfarki.subscreasy.client.model/SavedCard
   * @version 1.0
   */

  /**
   * Constructs a new <code>SavedCard</code>.
   * @alias module:com.kodfarki.subscreasy.client.model/SavedCard
   * @class
   */
  var exports = function() {
    var _this = this;











  };

  /**
   * Constructs a <code>SavedCard</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.kodfarki.subscreasy.client.model/SavedCard} obj Optional instance to populate.
   * @return {module:com.kodfarki.subscreasy.client.model/SavedCard} The populated <code>SavedCard</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('binNumber')) {
        obj['binNumber'] = ApiClient.convertToType(data['binNumber'], 'String');
      }
      if (data.hasOwnProperty('cardAlias')) {
        obj['cardAlias'] = ApiClient.convertToType(data['cardAlias'], 'String');
      }
      if (data.hasOwnProperty('cardAssociation')) {
        obj['cardAssociation'] = ApiClient.convertToType(data['cardAssociation'], 'String');
      }
      if (data.hasOwnProperty('cardBankCode')) {
        obj['cardBankCode'] = ApiClient.convertToType(data['cardBankCode'], 'Number');
      }
      if (data.hasOwnProperty('cardBankName')) {
        obj['cardBankName'] = ApiClient.convertToType(data['cardBankName'], 'String');
      }
      if (data.hasOwnProperty('cardFamily')) {
        obj['cardFamily'] = ApiClient.convertToType(data['cardFamily'], 'String');
      }
      if (data.hasOwnProperty('cardToken')) {
        obj['cardToken'] = ApiClient.convertToType(data['cardToken'], 'String');
      }
      if (data.hasOwnProperty('cardUserKey')) {
        obj['cardUserKey'] = ApiClient.convertToType(data['cardUserKey'], 'String');
      }
      if (data.hasOwnProperty('cartType')) {
        obj['cartType'] = ApiClient.convertToType(data['cartType'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} binNumber
   */
  exports.prototype['binNumber'] = undefined;
  /**
   * @member {String} cardAlias
   */
  exports.prototype['cardAlias'] = undefined;
  /**
   * @member {String} cardAssociation
   */
  exports.prototype['cardAssociation'] = undefined;
  /**
   * @member {Number} cardBankCode
   */
  exports.prototype['cardBankCode'] = undefined;
  /**
   * @member {String} cardBankName
   */
  exports.prototype['cardBankName'] = undefined;
  /**
   * @member {String} cardFamily
   */
  exports.prototype['cardFamily'] = undefined;
  /**
   * @member {String} cardToken
   */
  exports.prototype['cardToken'] = undefined;
  /**
   * @member {String} cardUserKey
   */
  exports.prototype['cardUserKey'] = undefined;
  /**
   * @member {String} cartType
   */
  exports.prototype['cartType'] = undefined;
  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;



  return exports;
}));


