/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';
import Company from './Company';

/**
 * The Subscriber model module.
 * @module com.kodfarki.subscreasy.client.model/Subscriber
 * @version 1.0.0
 */
class Subscriber {
    /**
     * Constructs a new <code>Subscriber</code>.
     * @alias module:com.kodfarki.subscreasy.client.model/Subscriber
     */
    constructor() { 
        
        Subscriber.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Subscriber</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.kodfarki.subscreasy.client.model/Subscriber} obj Optional instance to populate.
     * @return {module:com.kodfarki.subscreasy.client.model/Subscriber} The populated <code>Subscriber</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Subscriber();

            if (data.hasOwnProperty('billingAddress')) {
                obj['billingAddress'] = Address.constructFromObject(data['billingAddress']);
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = Company.constructFromObject(data['company']);
            }
            if (data.hasOwnProperty('createDate')) {
                obj['createDate'] = ApiClient.convertToType(data['createDate'], 'Date');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('identificationNo')) {
                obj['identificationNo'] = ApiClient.convertToType(data['identificationNo'], 'String');
            }
            if (data.hasOwnProperty('merchantSubscriberId')) {
                obj['merchantSubscriberId'] = ApiClient.convertToType(data['merchantSubscriberId'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
            if (data.hasOwnProperty('secureId')) {
                obj['secureId'] = ApiClient.convertToType(data['secureId'], 'String');
            }
            if (data.hasOwnProperty('shippingAddress')) {
                obj['shippingAddress'] = Address.constructFromObject(data['shippingAddress']);
            }
            if (data.hasOwnProperty('surname')) {
                obj['surname'] = ApiClient.convertToType(data['surname'], 'String');
            }
            if (data.hasOwnProperty('taxAdministration')) {
                obj['taxAdministration'] = ApiClient.convertToType(data['taxAdministration'], 'String');
            }
            if (data.hasOwnProperty('taxNumber')) {
                obj['taxNumber'] = ApiClient.convertToType(data['taxNumber'], 'String');
            }
            if (data.hasOwnProperty('worksFor')) {
                obj['worksFor'] = ApiClient.convertToType(data['worksFor'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:com.kodfarki.subscreasy.client.model/Address} billingAddress
 */
Subscriber.prototype['billingAddress'] = undefined;

/**
 * @member {module:com.kodfarki.subscreasy.client.model/Company} company
 */
Subscriber.prototype['company'] = undefined;

/**
 * @member {Date} createDate
 */
Subscriber.prototype['createDate'] = undefined;

/**
 * @member {String} email
 */
Subscriber.prototype['email'] = undefined;

/**
 * @member {Number} id
 */
Subscriber.prototype['id'] = undefined;

/**
 * @member {String} identificationNo
 */
Subscriber.prototype['identificationNo'] = undefined;

/**
 * @member {String} merchantSubscriberId
 */
Subscriber.prototype['merchantSubscriberId'] = undefined;

/**
 * @member {String} name
 */
Subscriber.prototype['name'] = undefined;

/**
 * @member {String} phoneNumber
 */
Subscriber.prototype['phoneNumber'] = undefined;

/**
 * @member {String} secureId
 */
Subscriber.prototype['secureId'] = undefined;

/**
 * @member {module:com.kodfarki.subscreasy.client.model/Address} shippingAddress
 */
Subscriber.prototype['shippingAddress'] = undefined;

/**
 * @member {String} surname
 */
Subscriber.prototype['surname'] = undefined;

/**
 * @member {String} taxAdministration
 */
Subscriber.prototype['taxAdministration'] = undefined;

/**
 * @member {String} taxNumber
 */
Subscriber.prototype['taxNumber'] = undefined;

/**
 * @member {String} worksFor
 */
Subscriber.prototype['worksFor'] = undefined;






export default Subscriber;

