/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Authority from './Authority';
import Company from './Company';

/**
 * The User model module.
 * @module com.kodfarki.subscreasy.client.model/User
 * @version 1.0.0
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * @alias module:com.kodfarki.subscreasy.client.model/User
     * @param activated {Boolean} 
     * @param companyOwner {Boolean} 
     * @param login {String} 
     */
    constructor(activated, companyOwner, login) { 
        
        User.initialize(this, activated, companyOwner, login);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, activated, companyOwner, login) { 
        obj['activated'] = activated;
        obj['companyOwner'] = companyOwner;
        obj['login'] = login;
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.kodfarki.subscreasy.client.model/User} obj Optional instance to populate.
     * @return {module:com.kodfarki.subscreasy.client.model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('activated')) {
                obj['activated'] = ApiClient.convertToType(data['activated'], 'Boolean');
            }
            if (data.hasOwnProperty('authorities')) {
                obj['authorities'] = ApiClient.convertToType(data['authorities'], [Authority]);
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = Company.constructFromObject(data['company']);
            }
            if (data.hasOwnProperty('companyOwner')) {
                obj['companyOwner'] = ApiClient.convertToType(data['companyOwner'], 'Boolean');
            }
            if (data.hasOwnProperty('createdDate')) {
                obj['createdDate'] = ApiClient.convertToType(data['createdDate'], 'Date');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('imageUrl')) {
                obj['imageUrl'] = ApiClient.convertToType(data['imageUrl'], 'String');
            }
            if (data.hasOwnProperty('langKey')) {
                obj['langKey'] = ApiClient.convertToType(data['langKey'], 'String');
            }
            if (data.hasOwnProperty('lastModifiedDate')) {
                obj['lastModifiedDate'] = ApiClient.convertToType(data['lastModifiedDate'], 'Date');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('login')) {
                obj['login'] = ApiClient.convertToType(data['login'], 'String');
            }
            if (data.hasOwnProperty('loginCount')) {
                obj['loginCount'] = ApiClient.convertToType(data['loginCount'], 'Number');
            }
            if (data.hasOwnProperty('resetDate')) {
                obj['resetDate'] = ApiClient.convertToType(data['resetDate'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} activated
 */
User.prototype['activated'] = undefined;

/**
 * @member {Array.<module:com.kodfarki.subscreasy.client.model/Authority>} authorities
 */
User.prototype['authorities'] = undefined;

/**
 * @member {module:com.kodfarki.subscreasy.client.model/Company} company
 */
User.prototype['company'] = undefined;

/**
 * @member {Boolean} companyOwner
 */
User.prototype['companyOwner'] = undefined;

/**
 * @member {Date} createdDate
 */
User.prototype['createdDate'] = undefined;

/**
 * @member {String} email
 */
User.prototype['email'] = undefined;

/**
 * @member {String} firstName
 */
User.prototype['firstName'] = undefined;

/**
 * @member {Number} id
 */
User.prototype['id'] = undefined;

/**
 * @member {String} imageUrl
 */
User.prototype['imageUrl'] = undefined;

/**
 * @member {String} langKey
 */
User.prototype['langKey'] = undefined;

/**
 * @member {Date} lastModifiedDate
 */
User.prototype['lastModifiedDate'] = undefined;

/**
 * @member {String} lastName
 */
User.prototype['lastName'] = undefined;

/**
 * @member {String} login
 */
User.prototype['login'] = undefined;

/**
 * @member {Number} loginCount
 */
User.prototype['loginCount'] = undefined;

/**
 * @member {Date} resetDate
 */
User.prototype['resetDate'] = undefined;






export default User;

