/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.ServiceOffering();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ServiceOffering', function() {
    it('should create an instance of ServiceOffering', function() {
      // uncomment below and update the code to test ServiceOffering
      //var instane = new ApiDocumentation.ServiceOffering();
      //expect(instance).to.be.a(ApiDocumentation.ServiceOffering);
    });

    it('should have the property company (base name: "company")', function() {
      // uncomment below and update the code to test the property company
      //var instane = new ApiDocumentation.ServiceOffering();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new ApiDocumentation.ServiceOffering();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new ApiDocumentation.ServiceOffering();
      //expect(instance).to.be();
    });

    it('should have the property offer (base name: "offer")', function() {
      // uncomment below and update the code to test the property offer
      //var instane = new ApiDocumentation.ServiceOffering();
      //expect(instance).to.be();
    });

    it('should have the property overUsagePrice (base name: "overUsagePrice")', function() {
      // uncomment below and update the code to test the property overUsagePrice
      //var instane = new ApiDocumentation.ServiceOffering();
      //expect(instance).to.be();
    });

    it('should have the property overUsageQuota (base name: "overUsageQuota")', function() {
      // uncomment below and update the code to test the property overUsageQuota
      //var instane = new ApiDocumentation.ServiceOffering();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instane = new ApiDocumentation.ServiceOffering();
      //expect(instance).to.be();
    });

    it('should have the property quotaAmount (base name: "quotaAmount")', function() {
      // uncomment below and update the code to test the property quotaAmount
      //var instane = new ApiDocumentation.ServiceOffering();
      //expect(instance).to.be();
    });

    it('should have the property service (base name: "service")', function() {
      // uncomment below and update the code to test the property service
      //var instane = new ApiDocumentation.ServiceOffering();
      //expect(instance).to.be();
    });

    it('should have the property unitName (base name: "unitName")', function() {
      // uncomment below and update the code to test the property unitName
      //var instane = new ApiDocumentation.ServiceOffering();
      //expect(instance).to.be();
    });

  });

}));
