/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.CompanyPropsResourceApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CompanyPropsResourceApi', function() {
    describe('createCompanyPropsUsingPOST', function() {
      it('should call createCompanyPropsUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createCompanyPropsUsingPOST
        //instance.createCompanyPropsUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCompanyPropsUsingDELETE', function() {
      it('should call deleteCompanyPropsUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteCompanyPropsUsingDELETE
        //instance.deleteCompanyPropsUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllCompanyPropsUsingGET', function() {
      it('should call getAllCompanyPropsUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAllCompanyPropsUsingGET
        //instance.getAllCompanyPropsUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCompanyPropsByCompanyIdUsingGET', function() {
      it('should call getCompanyPropsByCompanyIdUsingGET successfully', function(done) {
        //uncomment below and update the code to test getCompanyPropsByCompanyIdUsingGET
        //instance.getCompanyPropsByCompanyIdUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCompanyPropsUsingPUT', function() {
      it('should call updateCompanyPropsUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateCompanyPropsUsingPUT
        //instance.updateCompanyPropsUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
