/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.OrderItemResourceApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrderItemResourceApi', function() {
    describe('createOrderItemUsingPOST', function() {
      it('should call createOrderItemUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createOrderItemUsingPOST
        //instance.createOrderItemUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteOrderItemUsingDELETE', function() {
      it('should call deleteOrderItemUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteOrderItemUsingDELETE
        //instance.deleteOrderItemUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllOrderItemsUsingGET', function() {
      it('should call getAllOrderItemsUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAllOrderItemsUsingGET
        //instance.getAllOrderItemsUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrderItemUsingGET', function() {
      it('should call getOrderItemUsingGET successfully', function(done) {
        //uncomment below and update the code to test getOrderItemUsingGET
        //instance.getOrderItemUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateOrderItemUsingPUT', function() {
      it('should call updateOrderItemUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateOrderItemUsingPUT
        //instance.updateOrderItemUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
