/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.ServiceResourceApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ServiceResourceApi', function() {
    describe('createServiceUsingPOST', function() {
      it('should call createServiceUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createServiceUsingPOST
        //instance.createServiceUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteServiceUsingDELETE', function() {
      it('should call deleteServiceUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteServiceUsingDELETE
        //instance.deleteServiceUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllServicesUsingGET', function() {
      it('should call getAllServicesUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAllServicesUsingGET
        //instance.getAllServicesUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getServiceUsingGET', function() {
      it('should call getServiceUsingGET successfully', function(done) {
        //uncomment below and update the code to test getServiceUsingGET
        //instance.getServiceUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateServiceUsingPUT', function() {
      it('should call updateServiceUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateServiceUsingPUT
        //instance.updateServiceUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
