/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.UsageNotificationResourceApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsageNotificationResourceApi', function() {
    describe('createUsageNotificationUsingPOST', function() {
      it('should call createUsageNotificationUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createUsageNotificationUsingPOST
        //instance.createUsageNotificationUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUsageNotificationUsingDELETE', function() {
      it('should call deleteUsageNotificationUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteUsageNotificationUsingDELETE
        //instance.deleteUsageNotificationUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllUsageNotificationsUsingGET', function() {
      it('should call getAllUsageNotificationsUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAllUsageNotificationsUsingGET
        //instance.getAllUsageNotificationsUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUsageNotificationUsingGET', function() {
      it('should call getUsageNotificationUsingGET successfully', function(done) {
        //uncomment below and update the code to test getUsageNotificationUsingGET
        //instance.getUsageNotificationUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUsageNotificationUsingPUT', function() {
      it('should call updateUsageNotificationUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateUsageNotificationUsingPUT
        //instance.updateUsageNotificationUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
