/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.UserResourceApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserResourceApi', function() {
    describe('createUserUsingPOST', function() {
      it('should call createUserUsingPOST successfully', function(done) {
        //uncomment below and update the code to test createUserUsingPOST
        //instance.createUserUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserUsingDELETE', function() {
      it('should call deleteUserUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteUserUsingDELETE
        //instance.deleteUserUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllUsersUsingGET', function() {
      it('should call getAllUsersUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAllUsersUsingGET
        //instance.getAllUsersUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAuthoritiesUsingGET', function() {
      it('should call getAuthoritiesUsingGET successfully', function(done) {
        //uncomment below and update the code to test getAuthoritiesUsingGET
        //instance.getAuthoritiesUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserUsingGET', function() {
      it('should call getUserUsingGET successfully', function(done) {
        //uncomment below and update the code to test getUserUsingGET
        //instance.getUserUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUserUsingPUT', function() {
      it('should call updateUserUsingPUT successfully', function(done) {
        //uncomment below and update the code to test updateUserUsingPUT
        //instance.updateUserUsingPUT(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
